name: Build Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-svc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repository

      - uses: pmorelli92/github-container-registry-build-push@2.0.0
        name: Build and Publish latest service image
        with:
          github-push-secret: ${{secrets.GITHUB_TOKEN}}
          docker-image-name: neomutt-build
          docker-image-tag: latest # optional
          dockerfile-path: ./Dockerfile # optional
          # build-context: ./src/svc # optional

