# Create Ubuntu Docker image containing all the packages required for a full build of NeoMutt.
name: Build Docker Image
on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'Dockerfile'
  schedule:
    - cron: '0 3 1 * *'
      # 1st of the month at 03:00
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository

      - uses: pmorelli92/github-container-registry-build-push@2.0.0
        name: Build and Publish
        with:
          github-push-secret: ${{secrets.GITHUB_TOKEN}}
          docker-image-name: docker-build
          docker-image-tag: latest
          dockerfile-path: ./Dockerfile

