# Create Fedora Docker images containing all the packages required for a full build of NeoMutt.
name: Fedora
on:
  push:
  schedule:
    - cron: '0 3 1 * *'
      # 1st of the month at 03:00

jobs:
  build:
    strategy:
      matrix:
        cfg:
          - name: Fedora 34
            key: f34
          - name: Fedora 35
            key: f35
          - name: Fedora 36 (rawhide)
            key: f36

    name: Build ${{ matrix.cfg.name }}
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build ${{ matrix.cfg.name }}
        uses: pmorelli92/github-container-registry-build-push@2.0.0
        with:
          github-push-secret: ${{secrets.GITHUB_TOKEN}}
          docker-image-name: fedora
          docker-image-tag: ${{ matrix.cfg.key }}
          dockerfile-path: ./Dockerfile.${{ matrix.cfg.key }}

