# Create Fedora Docker images containing all the packages required for a full build of NeoMutt.
name: Fedora
on:
  push:
  schedule:
    - cron: '0 3 1 * *'
      # 1st of the month at 03:00

jobs:
  build:
    fail-fast: false
    strategy:
      matrix:
        cfg:
          - version: 34
          - version: 35
          - version: 36

    name: Build Fedora ${{ matrix.cfg.version }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Fedora ${{ matrix.cfg.version }}
        uses: pmorelli92/github-container-registry-build-push@2.0.0
        with:
          github-push-secret: ${{secrets.GITHUB_TOKEN}}
          docker-image-name: fedora
          docker-image-tag: ${{ matrix.cfg.version }}
          dockerfile-path: ./Dockerfile.f${{ matrix.cfg.version }}

