# Create Fedora Docker images containing all the packages required for a full build of NeoMutt.
name: Fedora
on:
  push:
    paths:
      - '.github/workflows/fedora.yml'
      - 'fedora.40/Dockerfile'
      - 'fedora.41/Dockerfile'
      - 'fedora.42/Dockerfile'
  schedule:
    - cron: '0 3 1 * *'
      # 1st of the month at 03:00
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - version: 40
          - version: 41
          - version: 42

    name: Build Fedora ${{ matrix.cfg.version }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Fedora ${{ matrix.cfg.version }}
        uses: pmorelli92/github-container-registry-build-push@2.2.1
        with:
          github-push-secret: ${{secrets.GITHUB_TOKEN}}
          docker-image-name: fedora
          docker-image-tag: ${{ matrix.cfg.version }}
          dockerfile-path: ./fedora.${{ matrix.cfg.version }}/Dockerfile

