# Create Ubuntu Docker image containing all the packages required for a full build of NeoMutt.
name: Ubuntu
on:
  push:
    paths:
      - '.github/workflows/ubuntu.yml'
      - 'ubuntu.24.04/Dockerfile'
  schedule:
    - cron: '0 3 1 * *'
      # 1st of the month at 03:00
  workflow_dispatch:

jobs:
  build:
    name: Build Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout repository

      - uses: pmorelli92/github-container-registry-build-push@2.2.1
        name: Build Ubuntu
        with:
          github-push-secret: ${{secrets.GITHUB_TOKEN}}
          docker-image-name: ubuntu
          docker-image-tag: latest
          dockerfile-path: ./ubuntu.24.04/Dockerfile

